#!/usr/bin/env python

from polarized.palette import Palette, ColorPicker, EGA
from polarized.image import Image
import png
import argparse

parser = argparse.ArgumentParser(description='Read PNG file and display it in your terminal')
parser.add_argument('input', help='input PNG file')

args = parser.parse_args()
reader = png.Reader(args.input)
w, h, pixels, info = reader.asRGB()
planes = info['planes']

#pal = Palette(16)
#
image = Image(w, h)
y = 0
for row in pixels:
	offset = 0
	for x in xrange(0, w):
		rgb = tuple(row[offset: offset + 3])
		image.set(y, x, rgb)
		offset += 3
	y += 1

#palette = pal.quantize()
#picker = ColorPicker(palette)
picker = ColorPicker(EGA)
closest = picker.getColor((255, 0, 255))
print closest
